spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  application:
    name: manage
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/WMCR?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: root
    
#mybatis    
mybatis:
  configuration:
    default-statement-timeout: 30
    map-underscore-to-camel-case: true
  mapper-locations:
  - classpath:/mapper/*/*.xml

logging:
  level: 
    com.jt.mapper: debug
  
server:
  port: 8080
  servlet:
    context-path: /
 
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka #http://eureka2:2002/eureka
      
#page
page.config: 
    pageSize: 5 
 