spring:
  thymeleaf:
    prefix: classpath:/templates/
  application:
    name: manage
    
server:
  port: 8080
  servlet:
    context-path: /
 
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka #http://eureka2:2002/eureka
 